name: Build ImmortalWrt N60Pro
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup build env
        uses: immortalwrt/setup-buildenv@main

      - name: Test echo
        run: echo "test ok"
